meta:
  id: combat_attack_config
  file-extension: tbl
  encoding: utf-8
  endian: le
seq:
  - id: table
    type: header
  - id: rows
    type: row
    repeat: expr
    repeat-expr: table.row_count
  - id: strings
    type: strz
    repeat: expr
    repeat-expr: table.unique_strings_count
types:
  header:
    seq:
      - id: version
        type: s4
      - id: descriptors_hash
        type: u4
      - id: layout_hash
        type: u4
      - id: table_version
        type: s4
      - id: row_count
        type: s4
      - id: string_data_size
        type: s4
      - id: unique_strings_count
        type: s4
  padding:
    seq:
      - id: padding_type
        size: 16
  row:
    seq:
      - id: combat_attack_config_id
        type: s4
      - id: combat_zone_id
        type: s4
      - id: combat_input_class_id
        type: s4
      - id: r_weapon_class_id
        type: s4
      - id: l_weapon_class_id
        type: s4
      - id: r_combat_weapon_group_id
        type: s4
      - id: l_combat_weapon_group_id
        type: s4
